using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Diagnostics.HealthChecks;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Swashbuckle.AspNetCore.Swagger;

//Health Checks
using HealthChecks.UI.Client;
using HealthChecks.UI.Configuration;
using HealthChecks.UI.Core;

//Custom Namespaces
using SEIS.Registration.Api.Helpers;
using SEIS.Registration.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using Microsoft.Extensions.Hosting;

namespace SEIS.Registration.Api
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc(options =>options.EnableEndpointRouting=false).SetCompatibilityVersion(CompatibilityVersion.Version_3_0);

            //Swagger Support
            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Version = "v1", Title = "SEIS Registration Web API", Description = "SEIS Registration Web API" });
                // Set the comments path for the Swagger JSON and UI.
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
                c.IncludeXmlComments(xmlPath);
            });

            var appSettingSection = Configuration.GetSection("AppSettings");
            services.Configure<AppSettings>(appSettingSection);

            //Health Checks
            services.AddHealthChecks()
                    .AddSqlServer(connectionString: Configuration.GetConnectionString("SqlServerConnection"),
                    healthQuery: "SELECT 1;", name: "Sql Server", failureStatus: HealthStatus.Degraded);

            //services.AddHealthChecksUI(setupSettings: setup =>
            //{
            //    setup.AddHealthCheckEndpoint("Basic HealthCheck", "https://localhost:44330/hc");
            //});
            // Set-up the plumming for our Identity server
            // We use "Bearer" which is the same output from Postman "token_type": "Bearer"
            // when we call https://localhost:44378/connect/token to grab a token
            services.AddAuthentication("Bearer")
                .AddIdentityServerAuthentication(options =>
                {
                    // This is the BankOfDotNet.IdentityServer which is running on port 5000
                    options.Authority = "https://localhost:44343";
                    options.RequireHttpsMetadata = true;
                    options.ApiName = "RegistrationAPI";
                });

            // Add a reference to the BankContext and use in-memory database
            services.AddDbContext<StudentContext>(options =>
                options.UseInMemoryDatabase("SEISDb"));

            //Register Services for Dependency Injection
            //services.RegisterServices();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            //app.UseHttpsRedirection();
            // Finally, we can make a call to our authentication service
            app.UseAuthentication();
            app.UseMvc();
            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "SEIS Registration Web API V1");

            });
        }
    }

    //#region Register Services
    //public static class ServiceCollectionExtensions
    //{
    //    /// <summary>
    //    /// Dependency Injection DI
    //    /// Register Services
    //    /// AddScoped means the instance of the class generated through DI will be valid for the duration of HTTP Request
    //    /// AddTransient  means a new instance of the class is generated by DI
    //    /// AddSingleton means one and only one instance of the class is generated.
    //    /// </summary>
    //    /// <param name="services"></param>
    //    /// <returns></returns>
    //    public static IServiceCollection RegisterServices(this IServiceCollection services)
    //    {

    //        services.AddScoped<IUserService, UserService>(); // or services.AddScoped(typeof(IUserService), typeof(UserService));
    //        return services;
    //    }
    //}
    //#endregion
}
